/* APPLICATION */
export const APP_KAKAO_INIT = "APP_KAKAO_INIT";

/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_KAKAO_LOGIN = "AUTH_KAKAO_LOGIN";
export const AUTH_KAKAO_SET_AUTH = "AUTH_KAKAO_SET_AUTH";
export const AUTH_KAKAO_LOGOUT = "AUTH_KAKAO_LOGOUT";
export const AUTH_KAKAO_GET_STATUS = "AUTH_KAKAO_GET_STATUS";
export const AUTH_KAKAO_GET_STATUS_SUCCESS = "AUTH_KAKAO_GET_STATUS_SUCCESS";
export const AUTH_KAKAO_GET_STATUS_FAILURE = "AUTH_KAKAO_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
