/* APPLICATION */

/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_KAKAO_LOGIN = "AUTH_KAKAO_LOGIN";
export const AUTH_KAKAO_SET_AUTH = "AUTH_KAKAO_SET_AUTH";
export const AUTH_KAKAO_LOGOUT = "AUTH_KAKAO_LOGOUT";
export const AUTH_KAKAO_GET_STATUS = "AUTH_KAKAO_GET_STATUS";
export const AUTH_KAKAO_GET_STATUS_SUCCESS = "AUTH_KAKAO_GET_STATUS_SUCCESS";
export const AUTH_KAKAO_GET_STATUS_FAILURE = "AUTH_KAKAO_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

/* ARTICLE */
export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";
export const GET_ARTICLE_LIST_FAILURE = "GET_ARTICLE_LIST_FAILURE";

export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILURE = "GET_ARTICLE_FAILURE";

export const REGISTER_ARTICLE = "REGISTER_ARTICLE";
export const REGISTER_ARTICLE_SUCCESS = "REGISTER_ARTICLE_SUCCESS";
export const REGISTER_ARTICLE_FAILURE = "REGISTER_ARTICLE_FAILURE";

export const MODIFY_ARTICLE = "REGISTER_ARTICLE";
export const MODIFY_ARTICLE_SUCCESS = "REGISTER_ARTICLE_SUCCESS";
export const MODIFY_ARTICLE_FAILURE = "REGISTER_ARTICLE_FAILURE";

export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_FAILURE = "REMOVE_ARTICLE_FAILURE";

export const GET_ARTICLE_TEMP = "GET_ARTICLE";
export const GET_ARTICLE_TEMP_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_TEMP_FAILURE = "GET_ARTICLE_FAILURE";

export const REGISTER_ARTICLE_TEMP = "REGISTER_ARTICLE";
export const REGISTER_ARTICLE_TEMP_SUCCESS = "REGISTER_ARTICLE_SUCCESS";
export const REGISTER_ARTICLE_TEMP_FAILURE = "REGISTER_ARTICLE_FAILURE";

export const MODIFY_ARTICLE_TEMP = "REGISTER_ARTICLE";
export const MODIFY_ARTICLE_TEMP_SUCCESS = "REGISTER_ARTICLE_SUCCESS";
export const MODIFY_ARTICLE_TEMP_FAILURE = "REGISTER_ARTICLE_FAILURE";

export const REMOVE_ARTICLE_TEMP = "REMOVE_ARTICLE";
export const REMOVE_ARTICLE_TEMP_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_TEMP_FAILURE = "REMOVE_ARTICLE_FAILURE";





